### ISSUE TITLE
Compatibility issues

### ISSUE THREAD

**Issue by luiscruz** [luiscruz/pyEnergiBridge#1]
The current version only works with Mac OS. 
I've only included my own binary of EnergiBridge.
Any help is appreciated!

**Comment by Khaleelhabeeb** [comment]
The reason might be because, the `energibridge` binary might be compiled specifically for macOS. If this binary contains macOS-specific system calls or dependencies, it will not run on other operating systems.

The best solution is by mocking the Subprocess call to allow testing of the subprocess functionality without depending on the actual energibridge binary

I will open a pull request with the probable solution

**Comment by luiscruz** [comment]
Hi @Khaleelhabeeb 
Thanks for your input! Indeed, you're right: the binary I am importing in the project was compiled for my machine only.
Another feature that could help here would be to allow users to configure their own binary. This could be set in a file stored in the home directory or in the project directory.
